language: python
python:
  - '3.6'
cache: pip

before_install:
  - sudo apt update
  - sudo apt install muscle
  - sudo apt install ncbi-blast+

install:
  - pip install -e .
branches:
  only:
    - master

before_script:
  - pip install codecov

script:
  - coverage run setup.py pytest

after_success:
  - codecov